version: '2'
services:
  proxy:
    image: soarinferret/iptablesproxy:latest
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - "SERVERIP=172.18.0.2"
      - "SERVERPORT=80"
      - "HOSTPORT=80"
    ports:
      - '8004:80'
    networks:
      - internet
      - no-internet
  web1:
    build:
      context: .
    networks:
      no-internet:
        ipv4_address: 172.18.0.2
    tty: True

networks:
  internet:
    driver: bridge
  no-internet:
    driver: bridge
    internal: true
    ipam:
      config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.1
